### ISSUE TITLE
Support for Git submodules

### ISSUE THREAD

**Issue by gmgunter** [henryiii/check-sdist#34]
Thanks for this nice tool!

I noticed that erroneous inconsistencies seem to be reported when the project contains Git submodules.

```
$ git clone https://github.com/isce-framework/snaphu-py.git
$ cd snaphu-py
$ pipx run check-sdist
[...]
SDist does not match git

SDist only:


Git only:
  ext/snaphu

```

In this case, `ext/snaphu` is a Git submodule whose contents are correctly included in the SDist, but `git ls-files` doesn't list them -- it only prints the top-level submodule directory name.

This could be resolved by adding the [`--recurse-submodules`](https://git-scm.com/docs/git-ls-files#Documentation/git-ls-files.txt---recurse-submodules) flag to the `git ls-files` command (requires Git >=[2.11.0](https://github.com/git/git/commit/1c2b1f7018ba7d5f6a5d949e29e4eaeeef3261e2)). Is that something you'd be interested in adding?

**Comment by henryiii** [comment]
Sure, that was the main issue holding back "1.0" IMO.
